name: "Build, run tests, collect coverage"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # first job
  ubuntu_gcc_code-coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Install dependencies
      #  run: |
      #    sudo apt-get install -y lcov
      #    lcov --version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and collect coverage
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCOLLECT_CODE_COVERAGE=OTHER -DGCOV_PATH=gcov-7 ..
          cmake --build .
          ctest -C Debug --output-on-failure
          ls -al

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
